runtime: nodejs18
env_variables:
  _DB_HOST: ##_DB_HOST##
  _DB_NAME: ##_DB_NAME##
  _DB_USER: ##_DB_USER##
  _DB_PASS: ##_DB_PASS##
  _JWT_SECRET: ##_JWT_SECRET##

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto