runtime: nodejs18
env_variables:
  _DB_HOST: "DB_HOST"
  _DB_NAME: "DB_NAME"
  _DB_USER: "DB_USER"
  _DB_PASS: "DB_PASS"
  _JWT_SECRET: "JWT_SECRET"

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto