runtime: nodejs18
env_variables:
  DB_HOST: %db_host%
  DB_NAME: %db_name%
  DB_USER: %db_user%
  DB_PASS: %db_pass%
  JWT_SECRET: %jwt_secret%

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto