runtime: nodejs18
env_variables:
  DB_HOST: "${_DB_HOST}"
  DB_NAME: "${_DB_NAME}"
  DB_USER: "${_DB_USER}"
  DB_PASS: "${_DB_PASS}"
  JWT_SECRET: "${_JWT_SECRET}"

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto