steps:
- name: node:18.16.0
  entrypoint: npm
  args: ["install"]
- name: node:18.16.0
  entrypoint: npm
  args: ["run", "create-env"]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: 
   - '-c'
   - |
      sed -i "s/##_DB_HOST##/${_DB_HOST}/g" app.yaml
      sed -i "s/##_DB_NAME##/${_DB_NAME}/g" app.yaml
      sed -i "s/##_DB_USER##/${_DB_USER}/g" app.yaml
      sed -i "s/##_DB_PASS##/${_DB_PASS}/g" app.yaml
      sed -i "s/##_JWT_SECRET##/${_JWT_SECRET}/g" app.yaml
      gcloud config set app/cloud_build_timeout 1600
      gcloud app deploy

# - name: "gcr.io/cloud-builders/gcloud"
#   args: ["app", "deploy"]
timeout: "1600s"
logsBucket: 'gs://artifacts.rentalbiz-387515.appspot.com'
serviceAccount: 'projects/rentalbiz-387515/serviceAccounts/cloudrun@rentalbiz-387515.iam.gserviceaccount.com'
options:
  logging: GCS_ONLY
