steps:
- name: node:18.16.0
  entrypoint: npm
  args: ["install"]
- name: node:18.16.0
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - 'DB_HOST=${_DB_HOST}'
    - 'DB_NAME=${_DB_NAME}'
    - 'DB_USER=${_DB_USER}'
    - 'DB_PASS=${_DB_PASS}'
    - 'JWT_SECRET=${_JWT_SECRET}'

- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
logsBucket: 'gs://artifacts.rentalbiz-387515.appspot.com'
serviceAccount: 'projects/rentalbiz-387515/serviceAccounts/cloudrun@rentalbiz-387515.iam.gserviceaccount.com'
options:
  logging: GCS_ONLY
