steps:
# Build the container image
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}', '.']
  id: Building the container image
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}']
  id: Pushing the image to registry
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_SERVICE_NAME}', '--image', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}', '--region', 'asia-east1', '--platform', 'managed', "--allow-unauthenticated", '--set-env-vars', 'DB_HOST="${_DB_HOST}"', '--set-env-vars', 'DB_NAME="${_DB_NAME}"', '--set-env-vars', 'DB_USER="${_DB_USER}"', '--set-env-vars', 'DB_PASS="${_DB_PASS}"', '--set-env-vars', 'JWT_SECRET="${_JWT_SECRET}"' ]
logsBucket: 'gs://artifacts.rentalbiz-387515.appspot.com'
serviceAccount: 'projects/rentalbiz-387515/serviceAccounts/cloudrun@rentalbiz-387515.iam.gserviceaccount.com'
options:
  logging: GCS_ONLY
